Plant_snoRNA_sequences.fasta contains plant specific snoRNAs from Plant snoRNA Database (http://bioinf.scri.sari.ac.uk/cgi-bin/plant_snorna/home).
tRNA.fasta and rRNA.fasta are plant specific tRNAs and rRNAs from NCBI Nucleotide database (http://www.ncbi.nlm.nih.gov/nuccore/) extracted with filters: 
  Species: Plants;
  Molecular types: rRNA/tRNA;
  Source databases: INSDC.
With searching keywords:
  'RNA', 'rRNA' and 'ribosome RNA' for rRNA;
  'RNA', 'tRNA' and 'transfer RNA' for tRNA.
